version: "3.9"
services:
    frontend:
        build: 
            context: ./frontend/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: frontend
        stdin_open: true
        networks:
            - application
    backend:
        build: 
            context: ./backend
        ports:
            - '5000:5000'
        container_name: backend
        networks: 
            - application
networks:
    application:
        driver: bridge

